version: '2'
services:
        mysql:
                image: mysql
                container_name: test-mysql
                ports:
                        - 6603:3306
                environment:
                        MYSQL_ROOT_PASSWORD: "toor"
                volumes:
                        - /storage/docker/mysql-datadir:/var/lib/mysql
                networks:
                        - php_mysql_net
        centos-php-mysql-apache:
                depends_on:
                        - mysql
                image: naqoda/centos-apache-php
                ports:
                        - 80:80
                volumes:
                        - "/srv/php-mysql-dockerCompose/sites/test/:/var/www/app/public_html/"
                links:
                        - mysql:mysql
                networks:
                        - php_mysql_net
networks:
        php_mysql_net:
                driver: bridge
